version: "3.8"

services:

  main:
    image: app
    build:
      context: .
    volumes:
      - .:/app/
      - /app/node_modules/
    command: npm run dev
    ports:
      - "${PORT_SERVER:-}:${PORT_SERVER:-}"
    expose:
      - ${PORT_SERVER:-}
    environment:
      # App config
      - PORT=${PORT_SERVER:-3002}
      # Database config
      - DB_HOST=${DB_HOST:-}
      - DB_USER=${DB_USER:-}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - DB_NAME=${DB_NAME:-}
      - DB_PORT=3306
      - DB_POOL_MAX=${DB_POOL_MAX:-}
      - DB_POOL_MIN=${DB_POOL_MIN:-}
      - DB_IDLE_TIMEOUT=${DB_IDLE_TIMEOUT:-}
      - DB_CONNECTION_TIMEOUT=${DB_CONNECTION_TIMEOUT:-}
      - DB_STATEMENT_TIMEOUT=${DB_STATEMENT_TIMEOUT:-}
      - DB_QUERY_TIMEOUT=${DB_QUERY_TIMEOUT:-}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-}
      - MYSQL_DATABASE=${DB_NAME:-}
      - MYSQL_USER=${DB_USER:-}
      - MYSQL_PASSWORD=${DB_PASSWORD:-}
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
